#!/usr/bin/env python3
"""Convert 'Vector (Stroke).svg' (Figma stroke-outline trace) into OpenSCAD polygon data.

The Figma export outlines the traced pen line, so every feature appears twice
(outer + inner contour of the stroke). We keep only:
  - subpath 0: outer contour of the part outline  -> filled solid
  - subpath 2: outer contour of the inner slot    -> cutout
  - circle subpath centers (left/right)           -> exported as positions

Output coordinates are in mm: scaled so the part is PART_LENGTH mm wide,
Y flipped (SVG is y-down), centered on the outline's bounding box center.

Usage: python3 svg_to_scad.py   (re-run if the SVG or PART_LENGTH changes)
"""
import re

SVG_FILE = "Vector (Stroke).svg"
OUT_FILE = "part_geometry.scad"
PART_LENGTH = 120.0  # mm, overall X extent of the part
BEZIER_SEGMENTS = 12


def parse_subpaths(d):
    tokens = re.findall(r"([MLHVCZmlhvcz])|(-?\d*\.?\d+(?:[eE][-+]?\d+)?)", d)
    stream = [t[0] if t[0] else float(t[1]) for t in tokens]
    subpaths, current, i, cmd = [], [], 0, None
    x = y = 0.0

    def num():
        nonlocal i
        v = stream[i]
        assert isinstance(v, float), f"expected number, got {v}"
        i += 1
        return v

    while i < len(stream):
        if isinstance(stream[i], str):
            cmd = stream[i]
            assert cmd.isupper(), f"relative command {cmd} not supported"
            i += 1
            if cmd == "Z":
                if current:
                    subpaths.append(current)
                current = []
                continue
        if cmd == "M":
            if current:
                subpaths.append(current)
                current = []
            x, y = num(), num()
            current.append((x, y))
            cmd = "L"  # subsequent implicit pairs are lineto
        elif cmd == "L":
            x, y = num(), num()
            current.append((x, y))
        elif cmd == "H":
            x = num()
            current.append((x, y))
        elif cmd == "V":
            y = num()
            current.append((x, y))
        elif cmd == "C":
            x1, y1, x2, y2, x3, y3 = (num() for _ in range(6))
            p0 = (x, y)
            for k in range(1, BEZIER_SEGMENTS + 1):
                t = k / BEZIER_SEGMENTS
                mt = 1 - t
                bx = mt**3 * p0[0] + 3 * mt**2 * t * x1 + 3 * mt * t**2 * x2 + t**3 * x3
                by = mt**3 * p0[1] + 3 * mt**2 * t * y1 + 3 * mt * t**2 * y2 + t**3 * y3
                current.append((bx, by))
            x, y = x3, y3
        else:
            raise ValueError(f"unhandled command {cmd}")
    if current:
        subpaths.append(current)
    return subpaths


def dedupe(pts, tol=1e-3):
    out = []
    for p in pts:
        if not out or abs(p[0] - out[-1][0]) > tol or abs(p[1] - out[-1][1]) > tol:
            out.append(p)
    if len(out) > 1 and abs(out[0][0] - out[-1][0]) <= tol and abs(out[0][1] - out[-1][1]) <= tol:
        out.pop()
    return out


def bbox(pts):
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def center(pts):
    x0, y0, x1, y1 = bbox(pts)
    return (x0 + x1) / 2, (y0 + y1) / 2


def main():
    svg = open(SVG_FILE).read()
    d = re.search(r'\bd="([^"]+)"', svg).group(1)
    subpaths = [dedupe(sp) for sp in parse_subpaths(d)]

    for idx, sp in enumerate(subpaths):
        x0, y0, x1, y1 = bbox(sp)
        print(f"subpath {idx}: {len(sp):4d} pts, bbox {x1-x0:8.1f} x {y1-y0:7.1f} at ({x0:.1f},{y0:.1f})")

    outline = subpaths[0]   # outer contour of part outline
    slot = subpaths[2]      # outer contour of inner slot
    left_hole = center(subpaths[4])
    right_hole = center(subpaths[5])

    x0, y0, x1, y1 = bbox(outline)
    s = PART_LENGTH / (x1 - x0)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2

    def tf(p):  # scale to mm, flip Y, center
        return round((p[0] - cx) * s, 4), round((cy - p[1]) * s, 4)

    def fmt(pts):
        return "[" + ", ".join(f"[{px}, {py}]" for px, py in (tf(p) for p in pts)) + "]"

    with open(OUT_FILE, "w") as f:
        f.write("// GENERATED by svg_to_scad.py from 'Vector (Stroke).svg' -- do not hand-edit.\n")
        f.write(f"// Part scaled to {PART_LENGTH} mm wide; coords in mm, centered, y-up.\n")
        f.write(f"outline_pts = {fmt(outline)};\n\n")
        f.write(f"slot_pts = {fmt(slot)};\n\n")
        f.write(f"left_hole_pos = [{tf(left_hole)[0]}, {tf(left_hole)[1]}];\n")
        f.write(f"right_hole_pos = [{tf(right_hole)[0]}, {tf(right_hole)[1]}];\n")

    print(f"\nwrote {OUT_FILE}: outline {len(outline)} pts, slot {len(slot)} pts")
    print(f"left hole center  (mm): {tf(left_hole)}")
    print(f"right hole center (mm): {tf(right_hole)}")


if __name__ == "__main__":
    main()
